name: benchmark-regression.yml

on: workflow_dispatch

jobs:
  build:
    if: ${{ always() }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        php: [8.4]
        stability: [prefer-stable]

    name: P${{ matrix.php }} - ${{ matrix.stability }} - ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: false
          fetch-depth: 0
          ref: ${{ github.head_ref || github.ref_name }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: ffi, pcntl, curl, bcmath
          coverage: none

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer update --${{ matrix.stability }} --prefer-dist --no-interaction

      - name: Dump autoload
        run: composer dump-autoload --optimize --apcu --no-cache

      - name: Run benchmark regression test
        run: composer benchmark-regression
