name: Benchmark regression test

on:
  pull_request:
    types: [labeled]
    branches: [ "main" ]

jobs:
  build:
    if: github.event.label.name == 'run-benchmark-regression'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        php: [8.4]

    name: Benchmark php-${{ matrix.php }} - ${{ matrix.os }}

    steps:
      - name: Checkout main to generate baseline
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Get last PHPBench tests and settings
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            test/Benchmark
            phpbench.json
          sparse-checkout-cone-mode: false
          path:
              current-phpbench-files

      - name: Use last PHPBench tests and settings
        run: |
          rm -rf test/Benchmark
          rm -f phpbench.json
          cp -R current-phpbench-files/test/Benchmark test/Benchmark
          cp current-phpbench-files/phpbench.json phpbench.json

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: ffi, pcntl, curl, bcmath
          coverage: none

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: php-composer-${{ matrix.php }}-${{ matrix.os }}-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            php-composer-${{ matrix.php }}-${{ matrix.os }}-

      - name: Install dependencies
        run: composer update --prefer-dist --no-interaction

      - name: Dump autoload
        run: composer dump-autoload --optimize --apcu --no-cache

      - run: mkdir -p .phpbench/samples
      - name: Cache Benchmark files
        uses: actions/cache@v3
        with:
          path: .phpbench/samples
          key: benchmark-samples-${{ hashFiles('/test/Benchmark/bootstrap.php') }}

      - name: Run benchmark to generate baseline
        run: |
          echo '## Main branch baseline' >> $GITHUB_STEP_SUMMARY 
          echo '' >> $GITHUB_STEP_SUMMARY
          echo '```markdown' >> $GITHUB_STEP_SUMMARY
          vendor/bin/phpbench run --tag=main --report=duckdb_benchmark_report --progress=none >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

      - name: Checkout current PR
        uses: actions/checkout@v4

      - name: Install dependencies for current PR
        run: composer update --prefer-dist --no-interaction

      - name: Dump autoload for current PR
        run: composer dump-autoload --optimize --apcu --no-cache

      - run: mkdir -p .phpbench/samples
      - name: Cache Benchmark files
        uses: actions/cache@v3
        with:
          path: .phpbench/samples
          key: benchmark-samples-${{ hashFiles('/test/Benchmark/bootstrap.php') }}

      - name: Run benchmark regression test
        run: |
          echo '## Regression results' >> $GITHUB_STEP_SUMMARY 
          echo '' >> $GITHUB_STEP_SUMMARY
          echo '```markdown' >> $GITHUB_STEP_SUMMARY
          vendor/bin/phpbench run --ref=main --report=duckdb_benchmark_report --progress=none >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
