name: PHPUnit (unstable - nightly C library)

on:
  schedule:
    - cron: "4 4 * * *"
  workflow_dispatch:


jobs:
  phpunit:
    uses: ./.github/workflows/php_test.yml
    with:
      lib-path: 'lib_nightly'