name: PHPUnit

on:
  workflow_call:
    inputs:
      lib-path:
        required: false
        type: string

permissions:
  contents: read

jobs:
  build:
    if: ${{ always() }}
    needs: [ get_nightly_libraries ]
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        php: [8.5, 8.4, 8.3]
        stability: [prefer-lowest, prefer-stable]
  
    name: P${{ matrix.php }} - ${{ matrix.stability }} - ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
      with:
        lfs: false

    - name: Libraries Cache
      id: libraries-cache
      uses: actions/cache@v3
      with:
        path: lib_nightly
        key: lib_nightly-${{ steps.get-date.outputs.date }}
        restore-keys: |
          lib_nightly
        enableCrossOsArchive: true

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: ffi, pcntl
        coverage: none

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer update --${{ matrix.stability }} --prefer-dist --no-interaction

    - name: Run test suite
      env:
        DUCKDB_PHP_LIB_DIRECTORY: ${{ inputs.lib-path }}
      run: vendor/bin/phpunit test

  get_nightly_libraries:
    if: ${{ inputs.lib-path }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: false

      - name: Libraries Cache
        id: libraries-cache
        uses: actions/cache@v3
        with:
          path: lib_nightly
          key: lib_nightly-${{ steps.get-date.outputs.date }}
          restore-keys: |
            lib_nightly

      - name: Get libraries
        run: ./scripts/get_libraries_nightly.sh