name: PHPUnit (stable)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  phpunit:
    uses: ./.github/workflows/php_test.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
